# **Notebook 00 - Procurando Dataset Experimental e fazendo leves testes nele com R:**


### **Ideia Inicial:** "Índice Paulista de Desenvolvimento Municipal — IPDM"

 - Descrição: Separa regiões de SP por nível de desenvolvimento econômico, emprego, etc.
 - Link Dataset: https://dadosabertos.sp.gov.br/dataset/indice-paulista-de-desenvolvimento-municipal-ipdm
 - Link Documentação:  https://repositorio.seade.gov.br/dataset/f714bdee-3f8c-464e-9e45-07a0e444937a/resource/f7b7a48d-3278-49ae-b152-25e5f006410f/download/ipdm_metodologia.pdf.
 - Link do Github onde baixei os dados (CSV): https://github.com/Megalonnix/Projeto_Integrador_PI3_2Sem_2026

### **1º Passo - Ler Dataset Escolhido:**
- **Nome dataset:** ipdm.csv
- **O que ele guarda? - Resposta:** Informações gerais sobre o **índice. Paulista. de. desenv. municipal (IPDM)** daquela cidade **X**.

In [ ]:
install.packages('tidyverse')

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [ ]:
library(glue)

usuario <- 'Megalonnix'
repositorio <- 'Projeto_Integrador_PI3_2Sem_2026'
nm_dataset_usado <- 'ipdm.csv'

# 1. Cria a URL correta com o "raw." no início e a barra antes do usuário
URL_GITHUB <- glue(
'https://raw.githubusercontent.com/{usuario}/{repositorio}/main/{nm_dataset_usado}')

# 2. Lê o arquivo CSV diretamente da internet
dados <- read.csv(URL_GITHUB, sep = ";", dec = ",", fileEncoding = 'Latin1')

In [ ]:
# 3. Dá um resumo do Dataset:

cat('RESUMO DOS DADOS (idpm.csv):\n\n') # equivale ao PRINT!!!
glimpse(dados)

RESUMO DOS DADOS (idpm.csv):

Rows: 61,920
Columns: 12
$ cod_ibge     <int> 3500105, 3500105, 3500105, 3500105, 3500105, 3500105, 350…
$ Municipio    <chr> "Adamantina", "Adamantina", "Adamantina", "Adamantina", "…
$ Valor        <dbl> 0.365, 0.365, 0.382, 0.378, 0.359, 0.381, 0.386, 0.356, 0…
$ Ano          <int> 2014, 2016, 2018, 2020, 2022, 2024, 2014, 2016, 2018, 202…
$ Tipo         <chr> "Riqueza", "Riqueza", "Riqueza", "Riqueza", "Riqueza", "R…
$ Valor.Estado <dbl> 0.457, 0.438, 0.451, 0.439, 0.441, 0.464, 0.457, 0.438, 0…
$ Indicador.1  <chr> "", "", "", "", "", "", "", "", "", "", "", "", "", "", "…
$ Indicador.2  <chr> "", "", "", "", "", "", "", "", "", "", "", "", "", "", "…
$ Indicador.3  <chr> "", "", "", "", "", "", "", "", "", "", "", "", "", "", "…
$ Indicador.4  <chr> "", "", "", "", "", "", "", "", "", "", "", "", "", "", "…
$ Indicador.5  <chr> "Indicador Riqueza", "Indicador Riqueza", "Indicador Riqu…
$ X            <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…

In [ ]:
# 4. Lê UMA PEQUENA PARTE do dataset (8 registros):

head(dados, n = 8)

  cod_ibge Municipio  Valor Ano  Tipo    Valor.Estado Indicador.1 Indicador.2
1 3500105  Adamantina 0.365 2014 Riqueza 0.457
2 3500105  Adamantina 0.365 2016 Riqueza 0.438
3 3500105  Adamantina 0.382 2018 Riqueza 0.451
4 3500105  Adamantina 0.378 2020 Riqueza 0.439
5 3500105  Adamantina 0.359 2022 Riqueza 0.441
6 3500105  Adamantina 0.381 2024 Riqueza 0.464
7 3500204  Adolfo     0.386 2014 Riqueza 0.457
8 3500204  Adolfo     0.356 2016 Riqueza 0.438
  Indicador.3 Indicador.4 Indicador.5       X
1                         Indicador Riqueza NA
2                         Indicador Riqueza NA
3                         Indicador Riqueza NA
4                         Indicador Riqueza NA
5                         Indicador Riqueza NA
6                         Indicador Riqueza NA
7                         Indicador Riqueza NA
8                         Indicador Riqueza NA

In [ ]:
# 4. Lê absolutamente TUDO:
dados

      cod_ibge Municipio              Valor Ano  Tipo    Valor.Estado
1     3500105  Adamantina             0.365 2014 Riqueza 0.457
2     3500105  Adamantina             0.365 2016 Riqueza 0.438
3     3500105  Adamantina             0.382 2018 Riqueza 0.451
4     3500105  Adamantina             0.378 2020 Riqueza 0.439
5     3500105  Adamantina             0.359 2022 Riqueza 0.441
6     3500105  Adamantina             0.381 2024 Riqueza 0.464
7     3500204  Adolfo                 0.386 2014 Riqueza 0.457
8     3500204  Adolfo                 0.356 2016 Riqueza 0.438
9     3500204  Adolfo                 0.412 2018 Riqueza 0.451
10    3500204  Adolfo                 0.442 2020 Riqueza 0.439
11    3500204  Adolfo                 0.401 2022 Riqueza 0.441
12    3500204  Adolfo                 0.427 2024 Riqueza 0.464
13    3500303  Aguaí                  0.348 2014 Riqueza 0.457
14    3500303  Aguaí                  0.323 2016 Riqueza 0.438
15    3500303  Aguaí                  0.353 2018 Riqueza 0.451
16    3500303  Aguaí                  0.349 2020 Riqueza 0.439
17    3500303  Aguaí                  0.352 2022 Riqueza 0.441
18    3500303  Aguaí                  0.387 2024 Riqueza 0.464
19    3500402  Águas da Prata         0.322 2014 Riqueza 0.457
20    3500402  Águas da Prata         0.292 2016 Riqueza 0.438
21    3500402  Águas da Prata         0.317 2018 Riqueza 0.451
22    3500402  Águas da Prata         0.317 2020 Riqueza 0.439
23    3500402  Águas da Prata         0.306 2022 Riqueza 0.441
24    3500402  Águas da Prata         0.326 2024 Riqueza 0.464
25    3500501  Águas de Lindóia       0.396 2014 Riqueza 0.457
26    3500501  Águas de Lindóia       0.391 2016 Riqueza 0.438
27    3500501  Águas de Lindóia       0.402 2018 Riqueza 0.451
28    3500501  Águas de Lindóia       0.379 2020 Riqueza 0.439
29    3500501  Águas de Lindóia       0.391 2022 Riqueza 0.441
30    3500501  Águas de Lindóia       0.421 2024 Riqueza 0.464
⋮     ⋮        ⋮                      ⋮     ⋮    ⋮       ⋮
61891 3554953  Tuiuti                 0.556 2024 IPDM    0.583
61892 3555000  Tupã                   0.597 2024 IPDM    0.583
61893 3555109  Tupi Paulista          0.606 2024 IPDM    0.583
61894 3555208  Turiúba                0.600 2024 IPDM    0.583
61895 3555307  Turmalina              0.668 2024 IPDM    0.583
61896 3555356  Ubarana                0.561 2024 IPDM    0.583
61897 3555406  Ubatuba                0.537 2024 IPDM    0.583
61898 3555505  Ubirajara              0.529 2024 IPDM    0.583
61899 3555604  Uchoa                  0.537 2024 IPDM    0.583
61900 3555703  União Paulista         0.539 2024 IPDM    0.583
61901 3555802  Urânia                 0.595 2024 IPDM    0.583
61902 3555901  Uru                    0.607 2024 IPDM    0.583
61903 3556008  Urupês                 0.628 2024 IPDM    0.583
61904 3556107  Valentim Gentil        0.547 2024 IPDM    0.583
61905 3556206  Valinhos               0.619 2024 IPDM    0.583
61906 3556305  Valparaíso             0.556 2024 IPDM    0.583
61907 3556354  Vargem                 0.527 2024 IPDM    0.583
61908 3556404  Vargem Grande do Sul   0.567 2024 IPDM    0.583
61909 3556453  Vargem Grande Paulista 0.580 2024 IPDM    0.583
61910 3556503  Várzea Paulista        0.547 2024 IPDM    0.583
61911 3556602  Vera Cruz              0.497 2024 IPDM    0.583
61912 3556701  Vinhedo                0.674 2024 IPDM    0.583
61913 3556800  Viradouro              0.545 2024 IPDM    0.583
61914 3556909  Vista Alegre do Alto   0.643 2024 IPDM    0.583
61915 3556958  Vitória Brasil         0.567 2024 IPDM    0.583
61916 3557006  Votorantim             0.563 2024 IPDM    0.583
61917 3557105  Votuporanga            0.640 2024 IPDM    0.583
61918 3557154  Zacarias               0.552 2024 IPDM    0.583
61919 3557204  Chavantes              0.505 2024 IPDM    0.583
61920 3557303  Estiva Gerbi           0.543 2024 IPDM    0.583
      Indicador.1 Indicador.2 Indicador.3 Indicador.4 Indicador.5       X
1                                                     Indicador Riqueza NA
2                                                     Indicador Riqueza NA
3                                                     Indicador Riqueza NA
4                                                     Indicador Riqueza NA
5                                                     Indicador Riqueza NA
6                                                     Indicador Riqueza NA
7                                                     Indicador Riqueza NA
8                                                     Indicador Riqueza NA
9                                                     Indicador Riqueza NA
10                                                    Indicador Riqueza NA
11                                                    Indicador Riqueza NA
12                                                    Indicador Riqueza NA
13                                                    Indicador Riqueza NA
14                                                    Indicador Riqueza NA
15                                                    Indicador Riqueza NA
16                                                    Indicador Riqueza NA
17                                                    Indicador Riqueza NA
18                                                    Indicador Riqueza NA
19                                                    Indicador Riqueza NA
20                                                    Indicador Riqueza NA
21                                                    Indicador Riqueza NA
22                                                    Indicador Riqueza NA
23                                                    Indicador Riqueza NA
24                                                    Indicador Riqueza NA
25                                                    Indicador Riqueza NA
26                                                    Indicador Riqueza NA
27                                                    Indicador Riqueza NA
28                                                    Indicador Riqueza NA
29                                                    Indicador Riqueza NA
30                                                    Indicador Riqueza NA
⋮     ⋮           ⋮           ⋮           ⋮           ⋮                 ⋮
61891                                                                   NA
61892                                                                   NA
61893                                                                   NA
61894                                                                   NA
61895                                                                   NA
61896                                                                   NA
61897                                                                   NA
61898                                                                   NA
61899                                                                   NA
61900                                                                   NA
61901                                                                   NA
61902                                                                   NA
61903                                                                   NA
61904                                                                   NA
61905                                                                   NA
61906                                                                   NA
61907                                                                   NA
61908                                                                   NA
61909                                                                   NA
61910                                                                   NA
61911                                                                   NA
61912                                                                   NA
61913                                                                   NA
61914                                                                   NA
61915                                                                   NA
61916                                                                   NA
61917                                                                   NA
61918                                                                   NA
61919                                                                   NA
61920                                                                   NA

In [ ]:
# 6. Controla melhor oqq eu quero ver:

getDadosFromMunicipio <- function(nmMunicipio, qtd_registros) {
 head(
  filter(dados, Municipio == nmMunicipio),
  n = qtd_registros)
}

In [ ]:
# 6A (Santos):
getDadosFromMunicipio("Santos", 5)

  cod_ibge Municipio Valor Ano  Tipo    Valor.Estado Indicador.1 Indicador.2
1 3548500  Santos    0.534 2014 Riqueza 0.457
2 3548500  Santos    0.505 2016 Riqueza 0.438
3 3548500  Santos    0.521 2018 Riqueza 0.451
4 3548500  Santos    0.502 2020 Riqueza 0.439
5 3548500  Santos    0.499 2022 Riqueza 0.441
  Indicador.3 Indicador.4 Indicador.5       X
1                         Indicador Riqueza NA
2                         Indicador Riqueza NA
3                         Indicador Riqueza NA
4                         Indicador Riqueza NA
5                         Indicador Riqueza NA

In [ ]:
#6B (GUARUJÁ):

getDadosFromMunicipio("Guarujá", 10)

   cod_ibge Municipio Valor Ano  Tipo        Valor.Estado Indicador.1
1  3518701  Guarujá   0.464 2014 Riqueza     0.457
2  3518701  Guarujá   0.437 2016 Riqueza     0.438
3  3518701  Guarujá   0.435 2018 Riqueza     0.451
4  3518701  Guarujá   0.426 2020 Riqueza     0.439
5  3518701  Guarujá   0.435 2022 Riqueza     0.441
6  3518701  Guarujá   0.399 2024 Riqueza     0.464
7  3518701  Guarujá   0.593 2014 Longevidade 0.698
8  3518701  Guarujá   0.633 2016 Longevidade 0.717
9  3518701  Guarujá   0.623 2018 Longevidade 0.721
10 3518701  Guarujá   0.617 2020 Longevidade 0.722
   Indicador.2 Indicador.3 Indicador.4 Indicador.5           X
1                                      Indicador Riqueza     NA
2                                      Indicador Riqueza     NA
3                                      Indicador Riqueza     NA
4                                      Indicador Riqueza     NA
5                                      Indicador Riqueza     NA
6                                      Indicador Riqueza     NA
7                                      Indicador Longevidade NA
8                                      Indicador Longevidade NA
9                                      Indicador Longevidade NA
10                                     Indicador Longevidade NA

In [ ]:
# 7. Mostrei TODOS os registros de Santos:
# filter(dados, Municipio == 'Santos') ********* FICA ENORME!!!!

In [ ]:
# 8. FILTRA OS DADOS, PEGA SÓ DA BAIXADA!!!!

cidades_baixada <- c("Santos", "São Vicente", "Guarujá", "Praia Grande",
                     "Cubatão", "Itanhaém", "Peruíbe", "Mongaguá", "Bertioga")

dados_baixada <- filter(dados,
                        Municipio %in% cidades_baixada)

In [ ]:
# lê 5 linhas de cada uma das cidades da BAIXADA (cada uma tem linha p/ cacete):

getDadosFrom_MunicipioBaixada <- function(nmMunicipio, qtd_registros) {
 head(
  filter(dados_baixada, Municipio == nmMunicipio),
  n = qtd_registros)
}

count <- 1
for (cidade in cidades_baixada) {
  cat("===========================================================================\n")
  cat(glue('Cidade Nº{count} | ( Nome = {cidade} )'))
  cat("\n===========================================================================\n\n")

  print(getDadosFrom_MunicipioBaixada(cidade, 3))
  cat('\n')
  count = count + 1
}

===========================================================================
Cidade Nº1 | ( Nome = Santos )
===========================================================================

  cod_ibge Municipio Valor  Ano    Tipo Valor.Estado Indicador.1 Indicador.2
1  3548500    Santos 0.534 2014 Riqueza        0.457
2  3548500    Santos 0.505 2016 Riqueza        0.438
3  3548500    Santos 0.521 2018 Riqueza        0.451
  Indicador.3 Indicador.4       Indicador.5  X
1                         Indicador Riqueza NA
2                         Indicador Riqueza NA
3                         Indicador Riqueza NA

===========================================================================
Cidade Nº2 | ( Nome = São Vicente )
===========================================================================

  cod_ibge   Municipio Valor  Ano    Tipo Valor.Estado Indicador.1 Indicador.2
1  3551009 São Vicente 0.380 2014 Riqueza        0.457
2  3551009 São Vicente 0.357 2016 Riqueza        0.438
3  3551009 São Vicente 0.363 2018 Riqueza        0.451
  Indicador.3 Indicador.4       Indicador.5  X
1                         Indicador Riqueza NA
2                         Indicador Riqueza NA
3                         Indicador Riqueza NA

===========================================================================
Cidade Nº3 | ( Nome = Guarujá )
===========================================================================

  cod_ibge Municipio Valor  Ano    Tipo Valor.Estado Indicador.1 Indicador.2
1  3518701   Guarujá 0.464 2014 Riqueza        0.457
2  3518701   Guarujá 0.437 2016 Riqueza        0.438
3  3518701   Guarujá 0.435 2018 Riqueza        0.451
  Indicador.3 Indicador.4       Indicador.5  X
1                         Indicador Riqueza NA
2                         Indicador Riqueza NA
3                         Indicador Riqueza NA

===========================================================================
Cidade Nº4 | ( Nome = Praia Grande )
===========================================================================

  cod_ibge    Municipio Valor  Ano    Tipo Valor.Estado Indicador.1 Indicador.2
1  3541000 Praia Grande 0.431 2014 Riqueza        0.457
2  3541000 Praia Grande 0.409 2016 Riqueza        0.438
3  3541000 Praia Grande 0.432 2018 Riqueza        0.451
  Indicador.3 Indicador.4       Indicador.5  X
1                         Indicador Riqueza NA
2                         Indicador Riqueza NA
3                         Indicador Riqueza NA

===========================================================================
Cidade Nº5 | ( Nome = Cubatão )
===========================================================================

  cod_ibge Municipio Valor  Ano    Tipo Valor.Estado Indicador.1 Indicador.2
1  3513504   Cubatão 0.524 2014 Riqueza        0.457
2  3513504   Cubatão 0.517 2016 Riqueza        0.438
3  3513504   Cubatão 0.498 2018 Riqueza        0.451
  Indicador.3 Indicador.4       Indicador.5  X
1                         Indicador Riqueza NA
2                         Indicador Riqueza NA
3                         Indicador Riqueza NA

===========================================================================
Cidade Nº6 | ( Nome = Itanhaém )
===========================================================================

  cod_ibge Municipio Valor  Ano    Tipo Valor.Estado Indicador.1 Indicador.2
1  3522109  Itanhaém 0.389 2014 Riqueza        0.457
2  3522109  Itanhaém 0.371 2016 Riqueza        0.438
3  3522109  Itanhaém 0.407 2018 Riqueza        0.451
  Indicador.3 Indicador.4       Indicador.5  X
1                         Indicador Riqueza NA
2                         Indicador Riqueza NA
3                         Indicador Riqueza NA

===========================================================================
Cidade Nº7 | ( Nome = Peruíbe )
===========================================================================

  cod_ibge Municipio Valor  Ano    Tipo Valor.Estado Indicador.1 Indicador.2
1  3537602   Peruíbe 0.379 2014 Riqueza        0.457
2  3537602   Peruíbe 0.354 2016 Riqueza        0.438
3  3537602   Peruíbe 0.389 2018 Riqueza        0.451
  Indicador.3 Indicador.4       Indicador.5  X
1                         Indicador Riqueza NA
2                         Indicador Riqueza NA
3                         Indicador Riqueza NA

===========================================================================
Cidade Nº8 | ( Nome = Mongaguá )
===========================================================================

  cod_ibge Municipio Valor  Ano    Tipo Valor.Estado Indicador.1 Indicador.2
1  3531100  Mongaguá 0.366 2014 Riqueza        0.457
2  3531100  Mongaguá 0.348 2016 Riqueza        0.438
3  3531100  Mongaguá 0.380 2018 Riqueza        0.451
  Indicador.3 Indicador.4       Indicador.5  X
1                         Indicador Riqueza NA
2                         Indicador Riqueza NA
3                         Indicador Riqueza NA

===========================================================================
Cidade Nº9 | ( Nome = Bertioga )
===========================================================================

  cod_ibge Municipio Valor  Ano    Tipo Valor.Estado Indicador.1 Indicador.2
1  3506359  Bertioga 0.575 2014 Riqueza        0.457
2  3506359  Bertioga 0.559 2016 Riqueza        0.438
3  3506359  Bertioga 0.548 2018 Riqueza        0.451
  Indicador.3 Indicador.4       Indicador.5  X
1                         Indicador Riqueza NA
2                         Indicador Riqueza NA
3                         Indicador Riqueza NA