# **Notebook 01 - Análise Exploratória Dataset (dados_ipdm.csv):**

In [27]:
# *********** AVISO!!!!! ************

# Se for a primeira vez rodando, remova o '#' das linhas abaixo:

# install.packages(
#     c("glue", 
#       "dplyr", 
#       "tidyverse"))

### **Fase 1 EDA (Exploratory Data Analysis) - Limpeza e Estruturação dos Dados**

In [28]:
library(glue)

usuario <- 'Megalonnix'
repositorio <- 'Projeto_Integrador_PI3_2Sem_2026'
nm_dataset_usado <- 'dados_ipdm.csv'

# 1. Cria a URL correta com o "raw." no início e a barra antes do usuário
URL_GITHUB <- glue(
'https://raw.githubusercontent.com/{usuario}/{repositorio}/main/{nm_dataset_usado}')

# 2. Lê o arquivo CSV diretamente da internet
df <- read.csv(URL_GITHUB, sep = ";", dec = ",", fileEncoding = 'Latin1')

In [29]:
# ---------------------------------------------------------
# BLOCO 1: Nomes das colunas e Tipos de Dados
# ---------------------------------------------------------

# Lista apenas os nomes das colunas
cat("--- LISTA DE COLUNAS ---\n")
print(colnames(df))

# Exibe a estrutura completa (Nome da coluna, Tipo de dado e Amostra dos valores)
cat("\n--- ESTRUTURA E TIPOS DE DADOS ---\n")
library(dplyr)
glimpse(df)

--- LISTA DE COLUNAS ---
 [1] "cod_ibge"     "Municipio"    "Valor"        "Ano"          "Tipo"
 [6] "Valor.Estado" "Indicador.1"  "Indicador.2"  "Indicador.3"  "Indicador.4"
[11] "Indicador.5"  "X"

--- ESTRUTURA E TIPOS DE DADOS ---
Rows: 61,920
Columns: 12
$ cod_ibge     <int> 3500105, 3500105, 3500105, 3500105, 3500105, 3500105, 350…
$ Municipio    <chr> "Adamantina", "Adamantina", "Adamantina", "Adamantina", "…
$ Valor        <dbl> 0.365, 0.365, 0.382, 0.378, 0.359, 0.381, 0.386, 0.356, 0…
$ Ano          <int> 2014, 2016, 2018, 2020, 2022, 2024, 2014, 2016, 2018, 202…
$ Tipo         <chr> "Riqueza", "Riqueza", "Riqueza", "Riqueza", "Riqueza", "R…
$ Valor.Estado <dbl> 0.457, 0.438, 0.451, 0.439, 0.441, 0.464, 0.457, 0.438, 0…
$ Indicador.1  <chr> "", "", "", "", "", "", "", "", "", "", "", "", "", "", "…
$ Indicador.2  <chr> "", "", "", "", "", "", "", "", "", "", "", "", "", "", "…
$ Indicador.3  <chr> "", "", "", "", "", "", "", "", "", "", "", "", "", "", "…
$ Indicador.4  <chr> "", "", "", "", "", "", "", "", "", "", "", "", "", "", "…
$ Indicador.5  <chr> "Indicador Riqueza", "Indicador Riqueza", "Indicador Riqu…
$ X            <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…

In [30]:
df <- df %>% select(-X)
glimpse(df)

Rows: 61,920
Columns: 11
$ cod_ibge     <int> 3500105, 3500105, 3500105, 3500105, 3500105, 3500105, 350…
$ Municipio    <chr> "Adamantina", "Adamantina", "Adamantina", "Adamantina", "…
$ Valor        <dbl> 0.365, 0.365, 0.382, 0.378, 0.359, 0.381, 0.386, 0.356, 0…
$ Ano          <int> 2014, 2016, 2018, 2020, 2022, 2024, 2014, 2016, 2018, 202…
$ Tipo         <chr> "Riqueza", "Riqueza", "Riqueza", "Riqueza", "Riqueza", "R…
$ Valor.Estado <dbl> 0.457, 0.438, 0.451, 0.439, 0.441, 0.464, 0.457, 0.438, 0…
$ Indicador.1  <chr> "", "", "", "", "", "", "", "", "", "", "", "", "", "", "…
$ Indicador.2  <chr> "", "", "", "", "", "", "", "", "", "", "", "", "", "", "…
$ Indicador.3  <chr> "", "", "", "", "", "", "", "", "", "", "", "", "", "", "…
$ Indicador.4  <chr> "", "", "", "", "", "", "", "", "", "", "", "", "", "", "…
$ Indicador.5  <chr> "Indicador Riqueza", "Indicador Riqueza", "Indicador Riqu…

In [31]:
as.list(colnames(df))

[[1]]
[1] "cod_ibge"

[[2]]
[1] "Municipio"

[[3]]
[1] "Valor"

[[4]]
[1] "Ano"

[[5]]
[1] "Tipo"

[[6]]
[1] "Valor.Estado"

[[7]]
[1] "Indicador.1"

[[8]]
[1] "Indicador.2"

[[9]]
[1] "Indicador.3"

[[10]]
[1] "Indicador.4"

[[11]]
[1] "Indicador.5"

In [32]:
colnames(df) <- c(
    "cod_ibge", 
    "municipio", 
    "valor", 
    "ano", 
    "tipo", 
    "valor_estado", 
    "indicador_1", 
    "indicador_2", 
    "indicador_3", 
    "indicador_4", 
    "indicador_5")

In [33]:
View(head(df, 3))

  cod_ibge municipio  valor ano  tipo    valor_estado indicador_1 indicador_2
1 3500105  Adamantina 0.365 2014 Riqueza 0.457
2 3500105  Adamantina 0.365 2016 Riqueza 0.438
3 3500105  Adamantina 0.382 2018 Riqueza 0.451
  indicador_3 indicador_4 indicador_5
1                         Indicador Riqueza
2                         Indicador Riqueza
3                         Indicador Riqueza

In [34]:
# ======================================
# Me livrando de dados vazios/nulos/etc ...
# ======================================

# 1. Tratamento de vírgulas para ponto
df$valor <- as.numeric(gsub(",", ".", df$valor))
df$valor_estado <- as.numeric(gsub(",", ".", df$valor_estado))

# 2. Filtro da coluna 'valor' (remove NAs e zeros)
df <- df[!is.na(df$valor) & df$valor != 0, ]

# 3. Limpeza manual de texto (municipio e tipo)
df <- df[!is.na(df$municipio) & trimws(df$municipio) != "", ]
df <- df[!is.na(df$tipo) & trimws(df$tipo) != "", ]

In [35]:
View(head(df, 3))

  cod_ibge municipio  valor ano  tipo    valor_estado indicador_1 indicador_2
1 3500105  Adamantina 0.365 2014 Riqueza 0.457
2 3500105  Adamantina 0.365 2016 Riqueza 0.438
3 3500105  Adamantina 0.382 2018 Riqueza 0.451
  indicador_3 indicador_4 indicador_5
1                         Indicador Riqueza
2                         Indicador Riqueza
3                         Indicador Riqueza

In [36]:
library(dplyr)

# 1. Filtra as notas padronizadas (0 a 1)
df_notas <- df %>% 
  filter(trimws(indicador_5) != "" | (valor <= 1 & valor_estado <= 1))

# 2. Filtra os dados brutos (reais, taxas, porcentagens, etc.)
df_brutos <- df %>% 
  filter(trimws(indicador_5) == "" & (valor > 1 | valor_estado > 1))

In [37]:
# Passo 0 - Captura o tipo de info. presente
# no Dom(C), no caso, Dom(coluna). 

get_resumo_colunas <- function(df, limite = 20) {

  tabela <- do.call(rbind, lapply(names(df), function(col) 
  {  
    x <- df[[col]]
    
    # Identifica o tipo
    tipo <- class(x)[1]
    if (is.character(x)) tipo <- "string"
    else if (is.logical(x)) tipo <- "boolean"
    else if (is.numeric(x)) tipo <- "numeric"
    
    # Processa o domínio
    vals <- unique(na.omit(x))
    qtd <- length(vals)
    
    if (is.numeric(x) && qtd > limite) {
      dom <- sprintf(
        "(%s, ..., %s)", 
        min(x, na.rm = TRUE), 
        max(x, na.rm = TRUE))
    } else if (qtd <= limite) {
      
      # Remove strings vazias da exibição visual se desejar
      vals_limpos <- vals[vals != ""] 
      dom <- sprintf(
        "(%s)", 
        paste(vals_limpos, collapse = ", "))
    } else {
      dom <- sprintf(
        "(%d valores distintos)", qtd)
    }
    
    data.frame(
      Coluna = col, 
      Tipo = tipo, 
      Dominio = dom, 
      stringsAsFactors = FALSE)
  }))
  
  return(tabela)
}

In [38]:
# Abre uma aba interativa estilo Excel/Matrix no RStudio
View(get_resumo_colunas(df))

   Coluna       Tipo
1  cod_ibge     numeric
2  municipio    string
3  valor        numeric
4  ano          numeric
5  tipo         string
6  valor_estado numeric
7  indicador_1  string
8  indicador_2  string
9  indicador_3  string
10 indicador_4  string
11 indicador_5  string
   Dominio
1  (3500105, ..., 3557303)
2  (645 valores distintos)
3  (0.140173816, ..., 732026.5279)
4  (2014, 2016, 2018, 2020, 2022, 2024)
5  (Riqueza, Longevidade, Escolaridade, IPDM)
6  (0.438, ..., 90454.96)
7  (Taxas de mortalidade infantil (por mil nascidos vivos), Taxas de atendimento escolar de crianças de 0 a 3 anos (%), Consumo anual de energia elétrica residencial (MWh) por ligação)
8  (Taxas de mortalidade perinatal (por mil nascidos vivos), Proporção média de alunos do 5º ano com proficiência em Língua Portuguesa e Matemática (%), Consumo anual de energia elétrica comercial, serviços e rural (MWh) por ligação)
9  (Taxas de mortalidade 15 a 39 anos (por mil hab.), Rendimento do trabalho formal mais benefícios previdenciarios per capita (R$ de 2024), Proporção média de  alunos do 9º ano com proficiência em Língua Portuguesa e Matemática (%))
10 (Taxas de mortalidade  60 a 69 anos (por mil hab.), Taxas de distorção idade-série no Ensino Médio (%), Produto Interno Bruto per capita (R$ de 2024))
11 (Indicador Riqueza, Indicador Longevidade, Indicador Escolaridade)

In [39]:
# Resumo enxuto focando APENAS em valor e valor_estado
get_resumo_valores <- function(df_notas, df_brutos) {
  data.frame(
    Dataframe = c("Notas (0 a 1)", "Notas (0 a 1)", "Dados Brutos", "Dados Brutos"),
    Coluna    = c("valor", "valor_estado", "valor", "valor_estado"),
    Minimo    = c(min(df_notas$valor, na.rm=TRUE), 
                  min(df_notas$valor_estado, na.rm=TRUE), 
                  min(df_brutos$valor, na.rm=TRUE), 
                  min(df_brutos$valor_estado, na.rm=TRUE)),
    Maximo    = c(max(df_notas$valor, na.rm=TRUE), 
                  max(df_notas$valor_estado, na.rm=TRUE), 
                  max(df_brutos$valor, na.rm=TRUE), 
                  max(df_brutos$valor_estado, na.rm=TRUE))
  )
}

# Execução
get_resumo_valores(df_notas, df_brutos)

  Dataframe     Coluna       Minimo    Maximo
1 Notas (0 a 1) valor        0.1450000      0.988
2 Notas (0 a 1) valor_estado 0.4380000      0.722
3 Dados Brutos  valor        0.1401738 732026.528
4 Dados Brutos  valor_estado 1.1500000  90454.960

In [40]:
View(head(df_notas, 6))

  cod_ibge municipio  valor ano  tipo    valor_estado indicador_1 indicador_2
1 3500105  Adamantina 0.365 2014 Riqueza 0.457
2 3500105  Adamantina 0.365 2016 Riqueza 0.438
3 3500105  Adamantina 0.382 2018 Riqueza 0.451
4 3500105  Adamantina 0.378 2020 Riqueza 0.439
5 3500105  Adamantina 0.359 2022 Riqueza 0.441
6 3500105  Adamantina 0.381 2024 Riqueza 0.464
  indicador_3 indicador_4 indicador_5
1                         Indicador Riqueza
2                         Indicador Riqueza
3                         Indicador Riqueza
4                         Indicador Riqueza
5                         Indicador Riqueza
6                         Indicador Riqueza

In [41]:
View(head(df_brutos, 6))

  cod_ibge municipio  valor    ano  tipo        valor_estado indicador_1
1 3500105  Adamantina 12.87996 2014 Longevidade 15.79
2 3500105  Adamantina 12.96720 2016 Longevidade 15.58
3 3500105  Adamantina 12.82766 2018 Longevidade 15.40
4 3500105  Adamantina 12.91236 2020 Longevidade 15.77
5 3500105  Adamantina 14.68354 2022 Longevidade 18.13
6 3500105  Adamantina 12.53548 2024 Longevidade 14.49
  indicador_2 indicador_3 indicador_4
1                         Taxas de mortalidade  60 a 69 anos (por mil hab.)
2                         Taxas de mortalidade  60 a 69 anos (por mil hab.)
3                         Taxas de mortalidade  60 a 69 anos (por mil hab.)
4                         Taxas de mortalidade  60 a 69 anos (por mil hab.)
5                         Taxas de mortalidade  60 a 69 anos (por mil hab.)
6                         Taxas de mortalidade  60 a 69 anos (por mil hab.)
  indicador_5
1
2
3
4
5
6